# https://taskfile.dev

version: "3"

tasks:
  adb:reverse:
    cmds:
      - "~/Android/Sdk/emulator/emulator -avd ssd-avd"
      # - adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; adb reverse tcp:8090 tcp:8090'
    silent: true

  build:apk:
    cmds:
      - flutter build apk --release
    silent: true

  emulators:
    cmds:
      - firebase emulators:start
    silent: true

  keystore:genkey:
    cmds:
      - keytool -genkey -v -keystore ~/development/keystore/taiwanswim.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias taiwanswimkey
    silent: true

  keystore:convertkey:
    cmds:
      - keytool -importkeystore -srckeystore product.jks -destkeystore product.jks -deststoretype pkcs12
    silent: true

  keystore:debugkey:
    cmds:
      - keytool -list -v -alias androiddebugkey -storepass android -keypass android -keystore ~/.android/debug.keystore
    silent: true

  open:ios:
    cmds:
      - open ios/Runner.xcworkspace
    silent: true
  
  open:android:
    cmds:
      - open -a /Applications/Android\ Studio.app android
    silent: true
